---
title: "FinalProject.Rmd"
author: "Group 9"
date: "12/1/2017"
resource_files:
- .Renviron
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
runtime: shiny
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
require(data.world)
require(MASS)
require(ISLR)
require(dplyr)
require(ggplot2)
```

## Non SELECT * SQL

Import the data from data.world, where the bulk of the work is done on the back end.

```{r}
project <- "https://data.world/rc38246/f-17-edv-project-5"
data.world::set_config(cfg_env("DW_API"))
schools <- data.world::query(
  data.world::qry_sql("SELECT s.latitude AS slat, s.longitude AS slong, school_name, a.latitude AS alat, a.longitude AS along, apartment_name FROM schools AS s cross join apartments AS a WHERE s.grades = 'Elementary' and school_type = 'public'"),
  dataset = project
  )
attach(schools)
```

## How many apartments are within a certain distance of how many public elementary schools?

```{r echo=FALSE}
R = 6371
deg2rad <- function(deg) {(deg * pi) / (180)}
# Determines the curvilinear distance between two coordinates in km
distances <- schools %>% dplyr::mutate(dLat = deg2rad(slat-alat), dLon = deg2rad(slong-along), a = sin(dLat/2)*sin(dLat/2)+cos(deg2rad(slat))*cos(deg2rad(alat))*sin(dLon/2)*sin(dLon/2), c = 2*atan2(sqrt(a), sqrt(1-a)), dist = R*c) %>% dplyr::select(school_name,apartment_name,dist)

# How many schools are within 5 km of each apartment
# grouped <- distances %>% dplyr::filter(dist <= 1) %>% dplyr::group_by(apartment_name) %>% dplyr::summarise(num_schools = n())

# how many apartments are within 5 km of how many schools
# regrouped <- grouped %>% dplyr::group_by(num_schools) %>% summarise(num_apartments = n())
sliderInput("range", "Range (in km):", min = 1, max = 10, value = 5)

renderPlot({
  distances %>% dplyr::filter(dist <= input$range) %>% dplyr::group_by(apartment_name) %>% dplyr::summarise(num_schools = n()) %>% ggplot(aes(num_schools)) + geom_bar()
})
# grouped <- data %>% dplyr::group_by(agent_key) %>% summarise(sum_with_offer = sum(calls_with_offer), sum_with_accept = sum(calls_with_accept), sum_offer_applied = sum(calls_offer_applied)) 
# 
# gathered <- grouped %>% tidyr::gather(variable,value, -agent_key)
# 
# renderPlot({
#   gathered %>% ggplot(aes(x = agent_key, y = value, color = variable)) + geom_smooth(se = FALSE)
# })
# 
# attach(grouped)
```

## dplyr Stuff

Looking into most successful agents and teams
topics coverered - piplines. select, mutate , group_by, summarize, arrange
```{r echo = FALSE}
# data_SA = data %>% dplyr::select(agent_key, agent_name, calls_with_accept, calls, team_lead_id) %>% dplyr::mutate(call_acceptance_rate = calls_with_accept / calls) %>% dplyr::group_by(agent_key, agent_name,team_lead_id) %>% dplyr::summarize(avg_calls_with_a = mean(calls_with_accept), avg_calls = mean(calls), avg_call_acceptance_rate = mean(call_acceptance_rate))
# 
# data_SA_sort = data_SA %>% dplyr::arrange(desc(avg_call_acceptance_rate))
# 
# data_SA_sort = data_SA %>% dplyr::arrange(avg_call_acceptance_rate)
# 
# teams = data_SA %>% dplyr::select(team_lead_id, avg_calls, avg_call_acceptance_rate) %>% dplyr::group_by(team_lead_id) %>% dplyr::summarize(mean(avg_calls), mean(avg_call_acceptance_rate))
# 
# renderPlot({
#   ggplot(data = teams, aes(x=`mean(avg_calls)`, y = `mean(avg_call_acceptance_rate)`)) + geom_line()
# })

```